[package]
description = "Platz Helm chart extensions"
edition = "2021"
license = "Apache-2.0"
name = "platz-chart-ext"
repository = "https://github.com/platzio/chart-ext"
version = "0.5.5"

[features]
default = []
utoipa = ["dep:utoipa"]

[dependencies]
anyhow = "1.0.56"
async-trait = "0.1.52"
reqwest = {version = "0.11.4", default-features = false, features = ["rustls-tls", "json"]}
rust_decimal = "1.22.0"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
serde_yaml = "0.9.9"
strum = {version = "0.24", features = ["derive"]}
thiserror = "1.0.30"
tokio = {version = "1", features = ["fs", "macros"]}
url = {version = "2.2.2", features = ["serde"]}
utoipa = {optional = true, version = "3", features = ["chrono", "decimal", "uuid"]}
uuid = {version = "1", features = ["v4"]}

[dev-dependencies]
anyhow = "1"
tokio = {version = "1", features = ["rt-multi-thread"]}
