name: 🧪 Test

on:
  pull_request:
  workflow_call:

jobs:
  test:
    name: 🧪 Test (${{ matrix.profile }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        profile:
          - debug
          - release
    steps:
      - name: 🛠 Checkout
        uses: actions/checkout@v4

      - name: 🔧 Install cargo-hack
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack

      - name: 📦 Cargo clippy (feature powerset)
        run: |
          cargo hack clippy --feature-powerset ${{ matrix.profile == 'release' && '--release' || '' }} -- -D warnings

      - name: 🧪 Cargo test (feature powerset)
        run: |
          cargo hack test --feature-powerset ${{ matrix.profile == 'release' && '--release' || '' }}
