name: 🧪 Test

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  fmt:
    name: 🎨 Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: 🛠 Checkout
        uses: actions/checkout@v6

      - name: 🧰 Install rustfmt
        run: rustup component add rustfmt

      - name: 🎨 Cargo fmt
        run: cargo fmt --all -- --check

  test:
    name: 🧪 ${{ matrix.task }} (${{ matrix.profile }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        profile:
          - debug
          - release
        task:
          - clippy
          - test
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: 🛠 Checkout
        uses: actions/checkout@v6

      - name: 🔧 Install cargo-hack
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack

      - name: 📦 Cargo ${{ matrix.task }} (feature powerset)
        run: |
          cargo hack ${{ matrix.task }} --feature-powerset ${{ matrix.profile == 'release' && '--release' || '' }}
